plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.diffplug.spotless'
}

android {
    namespace 'dev.tvvolume.app'
    compileSdk 34

    defaultConfig {
        applicationId "dev.tvvolume.app"
        minSdk 34
        targetSdk 34
        versionCode 21
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

spotless {
    kotlin {
        ktfmt()
        trimTrailingWhitespace()
        endWithNewline()
    }
}
